=== dvbtham/XML/07/bt_tonghop/cau2/sinhvien.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">
	<xs:element name="QuanLySinhVien">
		<xs:complexType>
			<xs:sequence>
				<!-- Thông tin sinh viên -->
				<xs:element name="SinhVien">	
					<xs:complexType>
						<xs:sequence>
						
						<xs:element name="MaSV">
						  <xs:simpleType>
							<xs:restriction base="xs:string">
							  <xs:pattern value="[A-Z][0-9]{2}"/>
							</xs:restriction>
						  </xs:simpleType>
						</xs:element>
						
						<xs:element name="HoSV" type="xs:string"/>
						
						<xs:element name="TenSV" type="xs:string"/>
						
						<xs:element name="Phai">
						  <xs:simpleType>
							<xs:restriction base="xs:string">
							  <!-- <xs:enumeration value="Nam"/>
							  <xs:enumeration value="Nữ"/> -->
							   <xs:pattern value="Nam|Nữ"/>
							</xs:restriction>
						  </xs:simpleType>
						</xs:element>
						
						<xs:element name="NgaySinh" type="xs:date"/>
						
						<xs:element name="NoiSinh" type="xs:string"/>
						
						<xs:element name="MaKhoa">
						  <xs:simpleType>
							<xs:restriction base="xs:string">
							  <xs:pattern value="[A-Z]{2}"/>
							</xs:restriction>
						  </xs:simpleType>
						</xs:element>
						
						<xs:element name="HocBong" type="xs:positiveInteger"/>
						
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- End thông tin sinh viên -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dvbtham/XML/07/bt_tonghop/cau2/qlsinhvien_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuanLySinhVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com file:///E:/ILearning/LTPM/XML/07/bt_tonghop/sinhvien.xsd" xmlns="http://www.w3schools.com">
	<SinhVien>
			<MaSV>A01</MaSV>
			<HoSV>Nguyễn Thị</HoSV>
			<TenSV>Hải</TenSV>
			<Phai>Nữ</Phai>
			<NgaySinh>1990-08-06</NgaySinh>
			<NoiSinh>Hà Nội</NoiSinh>
			<MaKhoa>TH</MaKhoa>
			<HocBong>2000000</HocBong>
	</SinhVien>
	
	<SinhVien>
			<MaSV>A02</MaSV>
			<HoSV>Nguyễn Thị</HoSV>
			<TenSV>Hải</TenSV>
			<Phai>Nữ</Phai>
			<NgaySinh>1990-08-06</NgaySinh>
			<NoiSinh>Hà Nội</NoiSinh>
			<MaKhoa>TH</MaKhoa>
			<HocBong>2000000</HocBong>
	</SinhVien>
	
	<SinhVien>
			<MaSV>A01</MaSV>
			<HoSV>Nguyễn Thị</HoSV>
			<TenSV>Hải</TenSV>
			<Phai>Nữ</Phai>
			<NgaySinh>1990-08-06</NgaySinh>
			<NoiSinh>Hà Nội</NoiSinh>
			<MaKhoa>TH</MaKhoa>
			<HocBong>2000000</HocBong>
	</SinhVien>
	</QuanLySinhVien>
