=== dvbtham/XML/02/DSNV.dtd
<!DOCTYPE danhsachnhanvien
[
<!ELEMENT danhsachnhanvien (nhanvien)*>
<!ELEMENT nhanvien (thongtincanhan,chucvu,bopphan,hocvan,bangluong)+>
<!ELEMENT thongtincanhan (soid,ten,ngaysinh,quequan)>
	<!ELEMENT soid (#PCDATA)>
	<!ELEMENT ten (#PCDATA)>
	<!ELEMENT ngaysinh (#PCDATA)>
	<!ELEMENT quequan (#PCDATA)> <!-- end thongtincanhan -->

<!ELEMENT chucvu (#PCDATA)>
<!ELEMENT bophan (#PCDATA)>
<!ELEMENT hocvan (#PCDATA)>

<!ELEMENT bangluong (hsluong,phucap,bhyt,bhxh)>
	<!ELEMENT hsluong (#PCDATA)>
	<!ELEMENT phucap (#PCDATA)>
	<!ELEMENT bhyt (#PCDATA)>
	<!ELEMENT bhxh (#PCDATA)> <!-- end bangluong -->

]>

=== dvbtham/XML/02/baitap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE danhsachnhanvien SYSTEM "DSNV.dtd">

<danhsachnhanvien>

	<nhanvien>

		<thongtincanhan>
			<soid> 33526</soid>
			<ten> Thâm</ten>
			<ngaysinh> 15/09/1996</ngaysinh>
			<quequan> Gia Lai</quequan>
		</thongtincanhan> <!-- End thongtincanhan -->

		<chucvu> Quản lý</chucvu>
		<bophan> Kinh doanh</bophan>
		<hocvan> Thạc sĩ</hocvan>

		<bangluong>

			<hsluong> 3.2</hsluong>
			<phucap> 5%</phucap>
			<bhyt> 50%</bhyt>
			<bhxh> 50%</bhxh>

		</bangluong> <!-- End bangluong -->

	</nhanvien> <!-- End -->

	<nhanvien>

		<thongtincanhan>
			<soid> 33527</soid>
			<ten> Nguyễn Viết Trí</ten>
			<ngaysinh> 15/09/1996</ngaysinh>
			<quequan> Đắc Lắk</quequan>
		</thongtincanhan> <!-- End thongtincanhan -->

		<chucvu> Quản lý</chucvu>
		<bophan> Kinh doanh</bophan>
		<hocvan> Thạc sĩ</hocvan>

		<bangluong>

			<hsluong> 3.2</hsluong>
			<phucap> 5%</phucap>
			<bhyt> 50%</bhyt>
			<bhxh> 50%</bhxh>

		</bangluong> <!-- End bangluong -->

	</nhanvien> <!-- End -->

	<nhanvien>

		<thongtincanhan>
			<soid> 33528</soid>
			<ten> Nguyễn Văn Duy</ten>
			<ngaysinh> 15/09/1996</ngaysinh>
			<quequan> Gia Lai</quequan>
		</thongtincanhan> <!-- End thongtincanhan -->

		<chucvu> Quản lý</chucvu>
		<bophan> Kinh doanh</bophan>
		<hocvan> Thạc sĩ</hocvan>

		<bangluong>

			<hsluong> 3.2</hsluong>
			<phucap> 5%</phucap>
			<bhyt> 50%</bhyt>
			<bhxh> 50%</bhxh>

		</bangluong> <!-- End bangluong -->

	</nhanvien> <!-- End -->
</danhsachnhanvien>
