=== dvbtham/XML/02/lichhoc.dtd
<!DOCTYPE phieulichhoc
[
<!ELEMENT phieulichhoc (sinhvien)*>
<!ELEMENT sinhvien (ttsinhvien,ttlichhoc)+>
	<!ELEMENT ttsinhvien (hoten,lop,diachi,ngaysinh)>
		<!ELEMENT hoten (#PCDATA)>
		<!ELEMENT lop (#PCDATA)>
		<!ELEMENT diachi (#PCDATA)>
		<!ELEMENT ngaysinh (#PCDATA)> <!-- end sinhvien -->

	<!ELEMENT ttlichhoc (stt,tenmonhoc,giaovien,thoigian,phonghoc)+>
		<!ELEMENT stt (#PCDATA)>
		<!ELEMENT tenmonhoc (#PCDATA)>
		<!ELEMENT giaovien (#PCDATA)>
		<!ELEMENT thoigian (#PCDATA)> 
		<!ELEMENT phonghoc (#PCDATA)><!-- end ttlichhoc -->

]>

=== dvbtham/XML/02/bt1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE phieulichhoc SYSTEM "lichhoc.dtd">
<phieulichhoc>
	<sinhvien>
		<ttsinhvien>
			<hoten> Thâm</hoten>
			<lop> CT14A1.11</lop>
			<diachi> Gia Lai</diachi>
			<ngaysinh> 15/09/1996</ngaysinh>
		</ttsinhvien>
		<ttlichhoc>
			<stt> 1</stt>
			<tenmonhoc> XML</tenmonhoc>
			<giaovien> Đặng Ngọc Huy</giaovien>
			<thoigian> 4 tiết</thoigian>
			<phonghoc> 106</phonghoc>
		</ttlichhoc>
	</sinhvien>
	<!-- end sinhvien -->
	<sinhvien>
		<ttsinhvien>
			<hoten> Nguyễn Viết Trí</hoten>
			<lop> CT14A1.11</lop>
			<diachi> Đắc Lắk</diachi>
			<ngaysinh> 15/09/1996</ngaysinh>
		</ttsinhvien>
		<ttlichhoc>
			<stt> 1</stt>
			<tenmonhoc> XML</tenmonhoc>
			<giaovien> Đặng Ngọc Huy</giaovien>
			<thoigian> 4 tiết</thoigian>
			<phonghoc> 106</phonghoc>
		</ttlichhoc>
	</sinhvien>
	<!-- end sinhvien -->
	<sinhvien>
		<ttsinhvien>
			<hoten> Nguyễn Hoàng Thịnh</hoten>
			<lop> CT14A1.11</lop>
			<diachi> Quảng Nam</diachi>
			<ngaysinh> 15/09/1996</ngaysinh>
		</ttsinhvien>
		<ttlichhoc>
			<stt> 1</stt>
			<tenmonhoc> XML</tenmonhoc>
			<giaovien> Đặng Ngọc Huy</giaovien>
			<thoigian> 4 tiết</thoigian>
			<phonghoc> 106</phonghoc>
		</ttlichhoc>
	</sinhvien>
	<!-- end sinhvien -->
</phieulichhoc>
