=== dvbtham/XML/02/phieudiem.dtd
<!DOCTYPE phieudiem
[
<!ELEMENT phieudiem (sinhvien)*>
<!ELEMENT sinhvien (ttsinhvien,ttphieudiem)+>
	<!ELEMENT ttsinhvien (hoten,lop,diachi,gioitinh,ngaysinh)>
		<!ELEMENT hoten (#PCDATA)>
		<!ELEMENT lop (#PCDATA)>
		<!ELEMENT diachi (#PCDATA)>
		<!ELEMENT gioitinh (#PCDATA)>
		<!ELEMENT ngaysinh (#PCDATA)> <!-- end sinhvien -->

	<!ELEMENT ttphieudiem (stt,tenmonhoc,diemcc,diembttrenlop,diembtvenha,diembtnhom,diembtlon,diemgiuaky,diemcuoiky,diemtrungbinh)+>
		<!ELEMENT stt (#PCDATA)>
		<!ELEMENT tenmonhoc (#PCDATA)>
		<!ELEMENT diemcc (#PCDATA)>
		<!ELEMENT diembttrenlop (#PCDATA)> 
		<!ELEMENT diembtvenha (#PCDATA)>
		<!ELEMENT diembtnhom (#PCDATA)>
		<!ELEMENT diembtlon (#PCDATA)>
		<!ELEMENT diemgiuaky (#PCDATA)>
		<!ELEMENT diemcuoiky (#PCDATA)>
		<!ELEMENT diemtrungbinh (#PCDATA)><!-- end ttphieudiem -->

]>

=== dvbtham/XML/02/bt2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE phieudiem SYSTEM "phieudiem.dtd">
<phieudiem>
	<sinhvien>
		<ttsinhvien>
			<hoten> Thâm</hoten>
			<lop> CT14A1.11</lop>
			<diachi> Gia Lai</diachi>
			<gioitinh> Nam</gioitinh>
			<ngaysinh> 15/09/1996</ngaysinh>
		</ttsinhvien>
		<ttphieudiem>
			<stt> 1</stt>
			<tenmonhoc> XML</tenmonhoc>
			<diemcc> 10</diemcc>
			<diembttrenlop> 8</diembttrenlop>
			<diembtvenha> 8</diembtvenha>
			<diembtnhom> 8</diembtnhom>
			<diembtlon> 8</diembtlon>
			<diemgiuaky> 8</diemgiuaky>
			<diemcuoiky> 8</diemcuoiky>
			<diemtrungbinh> 8</diemtrungbinh>
		</ttphieudiem>
	</sinhvien>
	<!--  end sinhvien -->
	<sinhvien>
		<ttsinhvien>
			<hoten> Nguyễn Viết Trí</hoten>
			<lop> CT14A1.11</lop>
			<diachi> Gia Lai</diachi>
			<gioitinh> Nam</gioitinh>
			<ngaysinh> 15/09/1996</ngaysinh>
		</ttsinhvien>
		<ttphieudiem>
			<stt> 1</stt>
			<tenmonhoc> XML</tenmonhoc>
			<diemcc> 10</diemcc>
			<diembttrenlop> 8</diembttrenlop>
			<diembtvenha> 8</diembtvenha>
			<diembtnhom> 8</diembtnhom>
			<diembtlon> 8</diembtlon>
			<diemgiuaky> 8</diemgiuaky>
			<diemcuoiky> 8</diemcuoiky>
			<diemtrungbinh> 8</diemtrungbinh>
		</ttphieudiem>
	</sinhvien>
	<!--  end sinhvien -->
	<sinhvien>
		<ttsinhvien>
			<hoten> Nguyễn Hoàng Thịnh</hoten>
			<lop> CT14A1.11</lop>
			<diachi> Gia Lai</diachi>
			<gioitinh> Nam</gioitinh>
			<ngaysinh> 15/09/1996</ngaysinh>
		</ttsinhvien>
		<ttphieudiem>
			<stt> 1</stt>
			<tenmonhoc> XML</tenmonhoc>
			<diemcc> 10</diemcc>
			<diembttrenlop> 8</diembttrenlop>
			<diembtvenha> 8</diembtvenha>
			<diembtnhom> 8</diembtnhom>
			<diembtlon> 8</diembtlon>
			<diemgiuaky> 8</diemgiuaky>
			<diemcuoiky> 8</diemcuoiky>
			<diemtrungbinh> 8</diemtrungbinh>
		</ttphieudiem>
	</sinhvien><!--  end sinhvien -->
</phieudiem>
