=== dvbtham/XML/03/tvschedule.dtd
<!DOCTYPE TVSCHEDULE
[
<!ELEMENT TVSCHEDULE (channel+)>
<!ELEMENT channel (banner,day+)>
		<!ELEMENT banner (#PCDATA)>
		<!ELEMENT day (date,(holiday|programslot+)+>
			<!ELEMENT date (#PCDATA)> 
			<!ELEMENT holiday (#PCDATA)> 
			<!ELEMENT programslot (time,title,description?)> 
				<!ELEMENT time (#PCDATA)> 
				<!ELEMENT title (#PCDATA)> 
				<!ELEMENT description (#PCDATA)> <!-- end channel -->
				
	<TVSCHEDULE name CDATA #REQUIRED>
	<channel chan CDATA #REQUIRED>
	<programslot vtr CDATA >
	<title rating CDATA >
	<title language CDATA >
	
]>

=== dvbtham/XML/03/tvcschedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TVSCHEDULE SYSTEM "tvschedule.dtd">

<TVSCHEDULE name="VTV3">
	<channel chan="hai">
		<banner> gap nhau cuoi tuan</banner>
		<day>
			<date>15/5/2016</date>
			<holiday>chuong trinh hai</holiday>
		</day>
	</channel>

	<channel chan="giaitri">
		<banner> chiec non ky dieu</banner>
		<day>
			<date>15/5/2016</date>
			<programslot vtr="yes">
				<time>12:00</time>
				<title>chu de dat nuoc con nguoi</title>
			</programslot>
		</day>
	</channel>

	<channel chan="phongsu">
		<banner> nhung neo duong dat nuoc</banner>
		<day>
			<date>15/5/2016</date>
			<programslot vtr="yes">
				<time>12:00</time>
				<title>nha trang</title>
				<description> khu du lich nha trang</description>
			</programslot>
		</day>
	</channel>

	<channel chan="thethao">
		<banner> chung ket champion</banner>
		<day>
			<date>15/5/2016</date>
			<programslot vtr="live">
				<time>12:00</time>
				<title>Real Madrid vs Barcelona</title>
				<description> truc tiep chung ket c1</description>
			</programslot>
		</day>
	</channel>
	
</TVSCHEDULE>
